[[plugins]]
  [plugins.inputs]    
    node_version = "16.x"

[build]
  command = "npm run build"
  functions = "/functions"
  publish = "client/dist"  # Adjust this path to match your build output

[build.environment]
  NETLIFY = "true"

[context.production.environment]
  NODE_ENV = "production"
