[[plugins]]
  package = "proj3"

  [plugins.inputs]    
    node_version = "16.x"

[build]
  command = "npm run install"
  functions = "/functions"

[build.environment]
  NETLIFY = "true"

[build.publish]
  directory = "client/dist"  # Adjust this path to match your build output

[context.production.environment]
  NODE_ENV = "production"
