services:
# STATIC SITE
- type: web
  name: JunkSpace
  runtime: static
  buildCommand: npm run build
  staticPublishPath: client/dist
  headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin
# BACKEND - DB
- type: web
  name: JunkSpace-DB
  runtime: node
  rootDir: server
  startCommand: npm run start