services:
# STATIC SITE
- type: web
  name: JunkSpace
  runtime: static
  buildCommand: npm run build
  staticPublishPath: client/dist
  headers:
    - path: /*
      name: X-Frame-Options
      value: sameorigin
    - path: https://junkspace-zcpt.onrender.com
      name: Referrer-Policy
      value: origin-when-cross-origin
# BACKEND - DB
- type: web
  name: JunkSpace-DB
  runtime: node
  buildCommand: npm install
  startCommand: cd server && npm run start